### ISSUE TITLE
добавить md в список поддерживаемых расширений для отчетов

### ISSUE THREAD

**Issue by zmm** [moevm/document_insight_system#466]
+ создать тестовую задачу и тестовый набор критериев (чтобы убедится, что нет больших проблем с их работой в новом формате)

**Comment by MarinaProsche** [comment]
Первая версия работы нового формата.
В начале файла "md_uploader.py" добавлен список проверок, которые доступны для набора критериев pack "BaseReportCriterionPackMd"
Все проверки работают корректно, кроме "needed_headers_check": список глав md-формата выводится в виде слишком больших заголовков(<h2>). Нужно уточнение, как именно исправить (добавлять ли условие в проверку или редактировать md_uploader)
Нужны добаботки.
Тестировалось на документах (нужны более "аккуратные" примеры):
[main_long_test.md](https://github.com/moevm/mse_auto_checking_slides_vaganov/files/13179604/main_long_test.md)
[example.md](https://github.com/moevm/mse_auto_checking_slides_vaganov/files/13179605/example.md)
https://github.com/moevm/mse_auto_checking_slides_vaganov/commit/7f666ceb069a37c359819d406d32ab7aeed09675
