### ISSUE TITLE
Набор критериев для проверки отчетов магистров по НИР 2 семестр 

### ISSUE THREAD

**Issue by zmm** [moevm/document_insight_system#477]
Нужно составить пак критериев (и задать соответствующие настройки)
1 Наличие разделов
- “Постановка задачи”
- “Результаты работы в весеннем семестре” и его подразделы "План" и "Результаты"
- "Описание предполагаемого метода решения”
- “План на осенний семестр”
- Список литературы

2 Корректные ссылки на иллюстративный материал
3 Доля изображений и таблиц в объеме
4 Корректные ссылки на литературу (== соблюдение уже существующих критериев)
5 Отсутствие упоминаний википедии (wikipedia.org)
6 Название файла - НОМЕР_ГРУППЫ-Фамилия_ИНИЦИАЛЫ_NIR2

**Comment by MarinaProsche** [comment]
Первая версия проверки НИР-2

https://github.com/moevm/mse_auto_checking_slides_vaganov/pull/479

**Comment by MarinaProsche** [comment]
Исправлено.
https://github.com/moevm/document_insight_system/pull/479
