### ISSUE TITLE
Ссылка на проверки пользователя на /results

### ISSUE THREAD

**Issue by HadronCollider** [moevm/document_insight_system#524]
- https://slides-checker.moevm.info/results/661007e52d0fc93a3d8b20b8

Ссылки :
- [Список всех загрузок пользователя](https://slides-checker.moevm.info/check_list?filter_user=dmitry.ivanov_e.moevm.info)
- [Cписок загрузок пользователя по критерию "LabReportPack"](https://slides-checker.moevm.info/check_list?filter_user=dmitry.ivanov_e.moevm.info&filter_criteria=LabReportPack)

должны вести на загрузки **пользователя данной проверки**, а не текущего пользователя, просматривающего страницу

**Comment by HadronCollider** [comment]
Вот тут берутся данные текущего пользователя - https://github.com/moevm/document_insight_system/blob/3b26f3cef7f78dc8524b779d7b26379dec6b3a09/app/templates/results.html#L57

а нужно брать данные юзера из проверки

**Comment by MarinaProsche** [comment]
Исправлено:
https://github.com/moevm/document_insight_system/pull/526
