### ISSUE TITLE
Критерий отчетов - ссылки на литературу

### ISSUE THREAD

**Issue by HadronCollider** [moevm/document_insight_system#560]
- отсутствие лишних символов
   - исправить регулярку (сейчас пропускает `[1.] [5.]`)
- проверка последовательности/упорядоченности ссылок (идет [12-13], а потом [1][2])

**Comment by MarinaProsche** [comment]
Вариант выполнения с комментариями:
https://github.com/moevm/document_insight_system/pull/565
