### ISSUE TITLE
Критерий для презентаций - подписи рисунков

### ISSUE THREAD

**Issue by zmm** [moevm/document_insight_system#574]
необходимо проверять, что у всех рисунков есть подпись Рисунок Х

**Comment by zmm** [comment]
Если слайд содержит единственный рисунок и название слайда отражает его, то нет необходимости подписывать рисунок.

**Comment by MarinaProsche** [comment]
https://github.com/moevm/document_insight_system/pull/596

Добавлено:
Поиск подписей и отображение всех найденных на странице результата для пользователя.
Проверка не пройдена если:
1) какой-либо из рисунков не подписан "Рисунок"
2) на странице находится Только рисунок и он подписан (в этом случае подпись необязательна)
